document.addEventListener("DOMContentLoaded", () => {
  const questions = [
    {category:"Phishing & email",q:"What is phishing?",o:["Antivirus scanning","Tricking users into revealing sensitive information","Data encryption","Firewall filtering"],a:1,e:"Phishing uses deception to steal information such as passwords, payment details or access credentials."},
    {category:"Phishing & email",q:"Which is a common warning sign of phishing?",o:["A message you expected","An urgent demand to act immediately","A saved contact","A normal company signature"],a:1,e:"Urgency creates pressure and reduces the chance that you will stop to verify the request."},
    {category:"Phishing & email",q:"What should you do before clicking a link in a message?",o:["Click quickly before it expires","Forward it to a colleague","Preview the destination and inspect the domain","Disable your antivirus"],a:2,e:"Previewing the link helps reveal misspelled, misleading or unfamiliar domains."},
    {category:"Phishing & email",q:"You receive an unexpected attachment from an unknown sender. What is the safest response?",o:["Open it in case it is important","Save it for later","Report the message and remove it","Rename the file"],a:2,e:"Unexpected attachments may contain malware. Report them through the appropriate channel without opening them."},
    {category:"Phishing & email",q:"What is spear phishing?",o:["A message sent randomly to millions","A telephone-only scam","A targeted message tailored to a person or organisation","A type of computer virus"],a:2,e:"Spear phishing uses personal or organisational details to make a targeted message more convincing."},
    {category:"Passwords & MFA",q:"Which password is strongest?",o:["Password123","Summer2026","P@ssword","9f#Q!Lk2@Zx8"],a:3,e:"A strong password is long, difficult to predict and unique to that account."},
    {category:"Passwords & MFA",q:"Why should you avoid reusing passwords?",o:["It slows down login","One breach could expose several accounts","It uses more device memory","It can disconnect Wi-Fi"],a:1,e:"Attackers test leaked credentials on other services. A unique password limits the damage from one breach."},
    {category:"Passwords & MFA",q:"What does multi-factor authentication add?",o:["A replacement for every password","Another form of identity verification","Automatic Wi-Fi encryption","A malware scanner"],a:1,e:"MFA requires another factor, so a stolen password alone is usually not enough to access the account."},
    {category:"Passwords & MFA",q:"Where is the best place to store many unique passwords?",o:["On a sticky note beside the device","In an email draft","In a reputable password manager","In the same unencrypted document"],a:2,e:"Password managers protect credentials and help generate strong, unique passwords."},
    {category:"Passwords & MFA",q:"You learn that one of your passwords has leaked. What should you do first?",o:["Ignore it until the account stops working","Change it immediately and check for reuse","Post the warning publicly","Restart the device"],a:1,e:"Change the exposed password immediately, update any reused passwords and enable MFA where possible."},
    {category:"Social engineering",q:"What does social engineering primarily target?",o:["Computer hardware","Network cables","People and their decisions","Firewall software"],a:2,e:"Social engineering manipulates human behaviour to gain information, money or access."},
    {category:"Social engineering",q:"What does pretexting mean?",o:["Installing malware","Using a fabricated story or identity","Encrypting a backup","Updating a system"],a:1,e:"A pretext is a believable scenario designed to persuade someone to disclose information or grant access."},
    {category:"Social engineering",q:"An authority-based attack may involve someone pretending to be:",o:["A random gamer","An unknown passer-by","A manager, IT technician or police officer","A fellow student with no request"],a:2,e:"Attackers impersonate authority figures because people are more likely to comply without questioning them."},
    {category:"Social engineering",q:"Which is an example of baiting?",o:["Installing an approved update","Leaving an enticing unknown USB drive to be found","Changing a firewall rule","Sending a routine backup reminder"],a:1,e:"Baiting uses curiosity or temptation to persuade someone to take a risky action."},
    {category:"Social engineering",q:"What is tailgating?",o:["Sending a fraudulent email","Following an authorised person into a restricted area","Infecting a USB drive","Attacking a VPN"],a:1,e:"Tailgating is a physical security breach where an unauthorised person follows someone through controlled access."},
    {category:"Malware & ransomware",q:"What is ransomware?",o:["A tracking cookie","Malware that locks or encrypts data and demands payment","A firewall feature","A backup application"],a:1,e:"Ransomware denies access to systems or data, often by encryption, and demands payment for recovery."},
    {category:"Malware & ransomware",q:"How can malware spread?",o:["Email attachments","Compromised websites","Removable drives","All of the above"],a:3,e:"Malware can spread through attachments, downloads, websites, removable media and many other routes."},
    {category:"Malware & ransomware",q:"What is spyware?",o:["Antivirus software","Software that secretly monitors activity or collects data","A VPN service","A backup tool"],a:1,e:"Spyware observes activity and collects information without the user's informed permission."},
    {category:"Malware & ransomware",q:"Which combination offers the best everyday protection against known malware?",o:["Disabling updates","Security software and timely updates","Using public Wi-Fi","Reusing passwords"],a:1,e:"Updates fix known vulnerabilities, while security tools can block or detect many common threats."},
    {category:"Malware & ransomware",q:"What should you do first if ransomware is suspected on a work device?",o:["Pay immediately","Disconnect it from networks and report it","Ignore the warning","Post a screenshot online"],a:1,e:"Isolation can reduce further spread. Report the incident immediately so the response process can begin."},
    {category:"Safe browsing & devices",q:"What is the safest way to reach a sensitive website such as online banking?",o:["Use a link from an unexpected email","Follow a pop-up advertisement","Use a trusted bookmark or type the known address","Choose any sponsored search result"],a:2,e:"A trusted bookmark or known address reduces the risk of reaching a convincing fake website."},
    {category:"Safe browsing & devices",q:"What does HTTPS tell you?",o:["The website is definitely trustworthy","The connection to the site is encrypted","The site cannot contain malware","The government verified the owner"],a:1,e:"HTTPS protects data in transit, but criminals can also use HTTPS. You must still verify the domain and content."},
    {category:"Safe browsing & devices",q:"What is a possible risk of untrusted public Wi-Fi?",o:["The device charges too quickly","Traffic interception or manipulation","Stronger encryption by default","There is no additional risk"],a:1,e:"A malicious or poorly secured network may allow attackers to observe or interfere with traffic."},
    {category:"Safe browsing & devices",q:"What should you do before installing software?",o:["Skip all information","Verify that the source is official and trusted","Disable security protection","Share the download link first"],a:1,e:"Use official, trusted sources and verify the publisher before installing software."},
    {category:"Safe browsing & devices",q:"Why should you lock your screen when stepping away?",o:["To save a small amount of battery","To prevent unauthorised access","To improve startup speed","To hide the wallpaper"],a:1,e:"A locked screen prevents another person from using your active session while the device is unattended."},
    {category:"Incident awareness",q:"Who is responsible for cyber security in an organisation?",o:["Only the IT department","Only senior managers","Everyone","Only external security specialists"],a:2,e:"Security is shared. Everyone's actions can help prevent, detect and report incidents."},
    {category:"Incident awareness",q:"You suspect a phishing message at work. What should you do?",o:["Reply to challenge the sender","Delete it without telling anyone","Report it through the approved channel, then remove it","Forward it to friends"],a:2,e:"Reporting helps security teams investigate the campaign and protect other people who may receive it."},
    {category:"Incident awareness",q:"Why is it useful to report small or uncertain incidents?",o:["To assign blame","They can reveal a larger pattern early","To create extra paperwork","For entertainment"],a:1,e:"Several small reports may expose a coordinated attack before it causes serious harm."},
    {category:"Incident awareness",q:"Why do attackers create urgency?",o:["To save you time","To reduce careful and rational thinking","To appear more professional","To encrypt the message"],a:1,e:"Time pressure encourages instinctive action and discourages independent verification."},
    {category:"Incident awareness",q:"What is the safest action when you are unsure whether a request is legitimate?",o:["Click the supplied link","Reply with the requested information","Verify it through a separate, trusted channel","Ignore every future message"],a:2,e:"Contact the person or organisation using trusted details—not the contact information supplied in the suspicious message."}
  ];

  const get = (id) => document.getElementById(id);
  const intro = get("quiz-intro"), app = get("quiz-app"), results = get("results-view"), questionCard = get("question-card");
  const categoryLabel = get("category-label"), questionCount = get("question-count"), progressPercent = get("progress-percent"), progressBar = get("progress-bar");
  const progressTrack = document.querySelector(".progress-track"), previousButton = get("previous-button"), checkButton = get("check-button"), nextButton = get("next-button");
  let current = 0, answers = new Array(questions.length).fill(null), revealed = new Array(questions.length).fill(false);

  function renderQuestion() {
    const item = questions[current], percent = Math.round(((current + 1) / questions.length) * 100);
    categoryLabel.textContent = item.category; questionCount.textContent = `Question ${current + 1} of ${questions.length}`; progressPercent.textContent = `${percent}%`; progressBar.style.width = `${percent}%`; progressTrack.setAttribute("aria-valuenow", String(percent));
    const options = item.o.map((option, index) => {
      const selected = answers[current] === index;
      let state = selected ? " selected" : "";
      if (revealed[current] && index === item.a) state += " correct";
      if (revealed[current] && selected && index !== item.a) state += " incorrect";
      return `<button class="answer-option${state}" type="button" data-answer="${index}" ${revealed[current] ? "disabled" : ""}><span class="answer-letter">${String.fromCharCode(65 + index)}</span><span>${option}</span><i aria-hidden="true"></i></button>`;
    }).join("");
    const feedback = revealed[current] ? `<div class="answer-feedback ${answers[current] === item.a ? "is-correct" : "is-incorrect"}"><strong>${answers[current] === item.a ? "Correct — well spotted." : `Not quite. The correct answer is ${String.fromCharCode(65 + item.a)}.`}</strong><p>${item.e}</p></div>` : "";
    questionCard.innerHTML = `<div class="question-number">Question ${String(current + 1).padStart(2,"0")}</div><h2>${item.q}</h2><div class="answer-list">${options}</div>${feedback}`;
    previousButton.disabled = current === 0; checkButton.classList.toggle("hidden", revealed[current]); nextButton.classList.toggle("hidden", !revealed[current]); checkButton.disabled = answers[current] === null; nextButton.textContent = current === questions.length - 1 ? "See my results →" : "Next question →";
    questionCard.querySelectorAll(".answer-option").forEach((button) => button.addEventListener("click", () => { answers[current] = Number(button.dataset.answer); renderQuestion(); }));
  }

  function showResults() {
    app.classList.add("hidden"); results.classList.remove("hidden");
    const score = answers.reduce((total, answer, index) => total + (answer === questions[index].a ? 1 : 0), 0), percent = Math.round((score / questions.length) * 100);
    const categories = [...new Set(questions.map((item) => item.category))];
    const breakdown = categories.map((category) => { const group = questions.map((item,index) => ({...item,index})).filter((item) => item.category === category); const correct = group.filter((item) => answers[item.index] === item.a).length; const pct = Math.round((correct / group.length) * 100); return `<div class="result-row"><div><span>${category}</span><small>${correct}/${group.length} correct</small></div><div class="result-meter"><i style="width:${pct}%"></i></div><strong>${pct}%</strong></div>`; }).join("");
    const wrong = questions.map((item,index) => ({...item,index})).filter((item) => answers[item.index] !== item.a);
    const review = wrong.length ? `<details class="review-panel"><summary>Review ${wrong.length} question${wrong.length === 1 ? "" : "s"} to revisit</summary><div>${wrong.map((item) => `<article><span>${item.category} · Question ${item.index + 1}</span><strong>${item.q}</strong><p>${item.e}</p></article>`).join("")}</div></details>` : `<div class="perfect-note">Excellent work—you answered every question correctly.</div>`;
    let level = "Developing awareness", message = "Review the explanations and focus on the categories with the lowest scores.";
    if (percent >= 90) { level = "Excellent awareness"; message = "You consistently recognised the safest response across the assessment."; }
    else if (percent >= 75) { level = "Strong awareness"; message = "You have a solid foundation. Review the few areas that caught you out."; }
    else if (percent >= 60) { level = "Good foundation"; message = "You recognise many common risks, with useful opportunities to strengthen your habits."; }
    results.innerHTML = `<div class="results-head"><div class="score-ring" style="--score:${percent * 3.6}deg"><div><strong>${percent}%</strong><span>${score}/${questions.length}</span></div></div><div><div class="eyebrow"><span></span> Assessment complete</div><h1>${level}</h1><p>${message}</p></div></div><div class="results-card"><div class="results-title"><h2>Your category breakdown</h2><span>Results</span></div>${breakdown}</div>${review}<div class="result-actions"><button class="button button-primary" id="restart-quiz" type="button">Retake assessment</button><a class="button button-secondary" href="contact.html">Share feedback</a></div>`;
    get("restart-quiz").addEventListener("click", restartQuiz); window.scrollTo({top:0,behavior:"smooth"});
  }
  function restartQuiz() { current = 0; answers = new Array(questions.length).fill(null); revealed = new Array(questions.length).fill(false); results.classList.add("hidden"); app.classList.remove("hidden"); renderQuestion(); window.scrollTo({top:0,behavior:"smooth"}); }
  get("start-quiz").addEventListener("click", () => { intro.classList.add("hidden"); app.classList.remove("hidden"); renderQuestion(); });
  checkButton.addEventListener("click", () => { if (answers[current] !== null) { revealed[current] = true; renderQuestion(); } });
  nextButton.addEventListener("click", () => { if (current === questions.length - 1) showResults(); else { current += 1; renderQuestion(); window.scrollTo({top:0,behavior:"smooth"}); } });
  previousButton.addEventListener("click", () => { if (current > 0) { current -= 1; renderQuestion(); } });
});
